### ISSUE TITLE
Mapping keycloak groups to Gerrit

### ISSUE THREAD

**Issue by finitha** [davido/keycloak-gerrit-oauth-provider#3]
Hello,

I havr installed the plugin in my gerrit website and I can now login in it using keycloak.

But, in Gerrit I don't have access to projets or changes. I tried to create an Administrators group in keycloak and assign it to my user but it doesn't work.

How can I add groups to my users using keycloak  and see it in Gerrit ?

Thanks !

**Comment by davido** [comment]
> But, in Gerrit I don't have access to projets or changes. 

Apparently your user is not administrator, for some reasons. In gerrit, the very first user that logged in into the system will become  admin user. You may ask admin user to add your new user to existing Administrators group in gerrit (not Keycloak Administrators group!).

> How can I add groups to my users using keycloak and see it in Gerrit ?

Group import from OAuth providers is currently not supported by gerrit-oauth-provider plugin.

Also note, that the right way to ask Gerrit and plugin related questions is to use repo-discuss mailing list: [1], or gerrit issue tracker to file feature requests: [2], or get invite for Slack channel to contact gerrit devs, see: [3] for details.

[1] https://groups.google.com/group/repo-discuss
[2] https://bugs.chromium.org/p/gerrit/issues/list
[3] https://www.gerritcodereview.com/support.html
